global_defs {
 # Don't run scripts configured to be run as root if any part of the path
 # is writable by a non-root user.
 enable_script_security
}
vrrp_script chk_haproxy {
 script "/usr/bin/pgrep haproxy"
 interval 2 # check every 2 seconds
 weight 2 # add 2 points of priority if OK
}
vrrp_instance VI_1 {
 interface eth0 # change here to match your network interface name.
 state MASTER # change here to BACKUP on the Backup server.
 virtual_router_id 51
 priority 101 # 101 master, 100 backup change here according to server
virtual_ipaddress {
  192.168.0.26
 }
track_script {
  chk_haproxy
 }
}
