# This is the network config written by 'subiquity'
network:
  ethernets:
    ens33:
        addresses: [192.168.101.135/24]
        nameservers:
            addresses : [8.8.8.8]
        routes:
            - to: default
              via: 192.168.101.2
